### ISSUE TITLE
无法实现永久保活-【结论：已修复】

### ISSUE THREAD

**Issue by lemongad** [fscarmen2/Render#1]
经部署探针，发现30分钟不到，就会失活，需要重新查看项目，然后会上线

**Comment by fscarmen2** [comment]
已修复，可以
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/92626977/216200324-8f1ae926-06ad-44c5-abf1-7b1f3efae06a.png">

如果仍然不行，就删了原实例，重新部署。

**Comment by 1234wei** [comment]
请问压缩文件是怎么运行的，设置什么变量？

**Comment by fscarmen2** [comment]
压缩文件是自动添加到容器内部运行的，已经打包在镜像处。
变量在项目首页有全部的了
https://github.com/fscarmen2/Render
