### ISSUE TITLE
自己不配置argo tunnel 临时生成的tunnel地址能用多久？

### ISSUE THREAD

**Issue by dinaau** [fscarmen2/Render#7]
就是全部默认配置

伪装域名是自动生成的一个临时地址

比如  : scary-papa-strategy-brothers.trycloudflare.com

请问这个地址能在一直用？所以render的节点能一直在线不断？

**Comment by fscarmen2** [comment]
容器平台，保不准他会因为母鸡问题重启的，所以还是推荐用固定的域名，当然你也可以测试一下临时域名是否长期有效，如果运行不了，再通过本项目的 /list 查最新的隧道名
